baseURL = "https://shroot.dev"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "Yazzyk's Blog"
themesDir = "themes"
theme = "White"
summaryLength = 100
hasCJKLanguage = true
paginate = 6
enableEmoji = true
enableRobotsTXT = true

[markup.highlight]
  codeFences = true
  guessSyntax = true
  style = 'native'
  lineNos = false
  lineNumbersInTable = true
  noClasses = true

[params]
  title = "Yazzyk's Blog"
  subTitle = "芝灵生于幽谷,不以无人而不芳"
  author = "Yazzyk"
  description = "Yazzyk's Blog"
  keyworlds = "Yazzyk,blog,paleblue,yk,hugo,caddy,Golang"
  record = ""
  policeRecordProvince = ""
  policeRecordNumber = ""
  linksFeedback = "交换友链请在下方留言,并将本站添加到贵站的友链中,且确保贵站支持HTTPS协议!"
  [params.seo]
    baidu = "code-TtzfDaB45q"
    googleSiteVerification = "kAjz9Ic_7Hir1rNUQtXSxTydJTryAv8JMelb2Qvnges"
  [params.valine]
    enable = false
    appId = "1qw0wI8rRU2aokRUy7A0Hzld-gzGzoHsz"
    appKey = "kTlur1J9v6jOExvFIlWM5jbp"
    placeholder = "Yo~"
    visitor = true
    highlight = true
    linksEnable = true
  [[params.social]]
    Icon = "fa-solid fa-envelope"
    Link = "mailto:917885215@qq.com"
  [[params.social]]
    Icon = "fa-brands fa-github"
    Link = "https://github.com/Yazzyk"
  [[params.social]]
    Icon = "fa-brands fa-qq"
    Link = "tencent://Message/?Uin=917885215&amp;websiteName=q-zone.qq.com&amp;Menu=yes"
  [[params.social]]
    Icon = "fa-solid fa-tv"
    Link = "https://space.bilibili.com/10061915"



[menu]

  [[menu.main]]
    url = "/"
    name = "欢迎页"
    weight = "10"
    identifier = "welcome"

  [[menu.main]]
    url = "/posts"
    name = "文章"
    weight = "20"
    identifier = "home"

  [[menu.main]]
    url = "/about"
    name = "关于我"
    weight = "30"
    identifier = "about"
  [[menu.main]]
    url = "/tags"
    name = "分类"
    weight = "40"
    identifier = "tags"
  [[menu.main]]
    url = "/links"
    name = "友链"
    weight = "50"
    identifier = "links"

  [[menu.links]]
    identifier = "Bamboo Sticks"
    name = "Bamboo Sticks"
    url = "https://haowei.ch/"

  [[menu.links]]
    identifier = "IUblog"
    name = "IUblog"
    url = "https://blog.iucode.cn/"

  [[menu.links]]
    identifier = "蠢黑通行"
    name = "蠢黑通行"
    url = "https://blackyau.cc/"

  [[menu.links]]
    identifier = "徐AB"
    name = "徐AB"
    url = "https://www.xuab.net/"

  [[menu.links]]
    identifier = "Water"
    name = "Water"
    url = "https://water1127.github.io"

  [[menu.links]]
    identifier = "CanYe"
    name = "CanYe"
    url = "http://blog.canye365.cn"

  [[menu.links]]
    identifier = "玄儿"
    name = "玄儿"
    url = "http://kirigayakazima.github.io"

  [[menu.links]]
    identifier = "Tmiracle"
    name = "Tmiracle"
    url = "https://texthub.cn/"

  [[menu.links]]
    identifier = "冰峰"
    name = "冰峰"
    url = "https://www.ad-s.cn/"
